"""Define durable delegation task application ports."""

from typing import Protocol

from aiserver.contracts.delegation import DelegationResult, DelegationTask, DelegationTaskRecord


class AgentTaskBus(Protocol):
    """Persist and lease durable agent-delegation tasks independently of audit events."""

    async def submit(self, task: DelegationTask) -> DelegationTaskRecord: ...
    async def claim_task(
        self, task_id: str, worker_id: str, *, lease_seconds: int = 60
    ) -> DelegationTaskRecord | None: ...
    async def claim(
        self, worker_id: str, *, limit: int = 1, lease_seconds: int = 60
    ) -> list[DelegationTaskRecord]: ...
    async def mark_running(self, task_id: str, worker_id: str) -> DelegationTaskRecord: ...
    async def complete(self, result: DelegationResult, worker_id: str) -> DelegationTaskRecord: ...
    async def fail(self, task_id: str, worker_id: str, error_code: str) -> DelegationTaskRecord: ...
    async def get(self, task_id: str) -> DelegationTaskRecord | None: ...