targets:
  dev:
    mode: development
    default: true
    workspace:
      host: https://dbc-baff2b7f-4402.cloud.databricks.com
      root_path: /Workspace/Users/${workspace.current_user.userName}/.bundle/${bundle.name}/${bundle.target}
      state_path: /Workspace/Users/${workspace.current_user.userName}/.bundle/${bundle.name}/${bundle.target}/state
    variables:
      app_name: multiagent-app-dev
      mlflow_experiment_id: "3025644123415124"
      openai_base_url: ""
      openai_timeout_seconds: "0"
      subagents_config_path: "/app/python/source_code/.venv/lib/python3.11/site-packages/backend/domain/subagents.dev.json"
      default_request_persona: "manager"
      app_telemetry_logs_table: "quickstart_catalog.multi_agent_schema.app_logs"
      app_telemetry_metrics_table: "quickstart_catalog.multi_agent_schema.app_metrics"
      app_telemetry_traces_table: "quickstart_catalog.multi_agent_schema.app_traces"
      genie_space_id: "01f159f5d91419549020e3609add391c"
      store_manager_genie_space_id: ""
      executive_genie_space_id: ""
      supply_chain_genie_space_id: ""
      cdi_genie_space_id: "01f19b2ab0f014daa3325ff30142f873"
      knowledge_assistant_endpoint_name: ""
      ai_search_endpoint_name: "product-search-vs-endpoint"
      flink_support_vs_endpoint_name: "flink-support-vs-endpoint"
      lakebase_project_id: "3ab05603-06dc-4789-a7fb-234d22a71e4b"
      lakebase_branch_id: "br-fragrant-sea-d1h720m5"
      lakebase_database: "operationaldatastore"
      lakebase_sql_warehouse_id: "ep-falling-cake-d1j29nc5"
      lakebase_pg_password: "Lkb-M4g3nt-0ds-2026!"
      message_bus_backend: uc_table
      message_bus_topic: agent-lifecycle-events
      uc_audit_warehouse_id: "b20f70f71c2f52e2"
      uc_audit_catalog: "quickstart_catalog"
      uc_audit_schema: "multi_agent_schema"
      uc_audit_table: agent_lifecycle_events
    resources:
      apps:
        multiagent-app:
          name: multiagent-app-dev
          usage_policy_id: "06846952-d579-4cd7-ab90-b86f0a1e3ed7"
          resources:
          - name: sales_genie_space
            genie_space:
              name: Sales Analysis Agent
              space_id: ${var.genie_space_id}
              permission: 'CAN_RUN'
          - name: cdi_genie_space
            genie_space:
              name: CDI Metrics Agent
              space_id: ${var.cdi_genie_space_id}
              permission: 'CAN_RUN'
          - name: lakebase_ods
            postgres:
              id: ${var.lakebase_sql_warehouse_id}
              permission: 'CAN_USE'